# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f55b63cf83c44ccf2719e7f358cbe15"
name = "SimplePost"
handle = "app-1087"
application_url = "https://orders-standing-stays-fountain.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "niko-wonderwork.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://orders-standing-stays-fountain.trycloudflare.com/auth/callback",
  "https://orders-standing-stays-fountain.trycloudflare.com/auth/shopify/callback",
  "https://orders-standing-stays-fountain.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
