# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f55b63cf83c44ccf2719e7f358cbe15"
name = "SimplePost"
handle = "app-1087"
application_url = "https://mixed-expenditure-ran-maximum.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "niko-wonderwork.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,read_script_tags,read_themes,write_product_listings,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://mixed-expenditure-ran-maximum.trycloudflare.com/auth/callback",
  "https://mixed-expenditure-ran-maximum.trycloudflare.com/auth/shopify/callback",
  "https://mixed-expenditure-ran-maximum.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
