# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "340aa3bcecced4a475bfa18aa973eab8"
name = "min-max-app"
handle = "min-max-app-2"
application_url = "https://enables-timothy-plaintiff-qualities.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "germiny.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = [
  "https://enables-timothy-plaintiff-qualities.trycloudflare.com/auth/callback",
  "https://enables-timothy-plaintiff-qualities.trycloudflare.com/auth/shopify/callback",
  "https://enables-timothy-plaintiff-qualities.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
