# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1f55b63cf83c44ccf2719e7f358cbe15"
name = "SimplePost"
handle = "app-1087"
application_url = "https://dividend-continental-advanced-ladder.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "niko-wonderwork.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_product_listings,read_products,read_script_tags,read_themes,write_product_listings,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://dividend-continental-advanced-ladder.trycloudflare.com/auth/callback",
  "https://dividend-continental-advanced-ladder.trycloudflare.com/auth/shopify/callback",
  "https://dividend-continental-advanced-ladder.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks"
  include_fields = [
    "admin_graphql_api_id",
    "app_id",
    "billing_address",
    "browser_ip",
    "buyer_accepts_marketing",
    "cancel_reason",
    "cancelled_at",
    "cart_token",
    "checkout_id",
    "checkout_token",
    "client_details",
    "closed_at",
    "confirmation_number",
    "confirmed",
    "contact_email",
    "created_at",
    "currency",
    "current_subtotal_price",
    "current_subtotal_price_set",
    "current_total_additional_fees_set",
    "current_total_discounts",
    "current_total_discounts_set",
    "current_total_duties_set",
    "current_total_price",
    "current_total_price_set",
    "current_total_tax",
    "current_total_tax_set",
    "device_id",
    "discount_applications",
    "discount_codes",
    "email",
    "estimated_taxes",
    "financial_status",
    "fulfillment_status",
    "fulfillments",
    "id",
    "landing_site",
    "landing_site_ref",
    "line_items",
    "location_id",
    "merchant_of_record_app_id",
    "name",
    "note",
    "note_attributes",
    "number",
    "order_number",
    "order_status_url",
    "original_total_additional_fees_set",
    "original_total_duties_set",
    "payment_gateway_names",
    "payment_terms",
    "phone",
    "po_number",
    "presentment_currency",
    "processed_at",
    "reference",
    "referring_site",
    "refunds",
    "source_identifier",
    "source_name",
    "source_url",
    "subtotal_price",
    "subtotal_price_set",
    "tags",
    "tax_exempt",
    "tax_lines",
    "taxes_included",
    "test",
    "token",
    "total_discounts",
    "total_discounts_set",
    "total_line_items_price",
    "total_line_items_price_set",
    "total_outstanding",
    "total_price",
    "total_price_set",
    "total_shipping_price_set",
    "total_tax",
    "total_tax_set",
    "total_tip_received",
    "total_weight",
    "updated_at",
    "user_id"
  ]

[pos]
embedded = false
